# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51bdced978e33c831e9ebf8d7123578d"
name = "test-template-app"
application_url = "https://used-urban-dramatically-bulk.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-pod-app-new.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_themes"

[auth]
redirect_urls = [
  "https://used-urban-dramatically-bulk.trycloudflare.com/auth/callback",
  "https://used-urban-dramatically-bulk.trycloudflare.com/auth/shopify/callback",
  "https://used-urban-dramatically-bulk.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
